services:
  server:
    image: alialahmad/backendimage:latest
    environment:
      - DB_HOST=database
      - DB_NAME=value
      - DB_USER=value
      - DB_PASSWORD=value
      - DB_PORT=3306
      - OPENAI_API_KEY=value
      - REPLICATE_API_TOKEN=value
      - JWT_SECRET=value
      - JWT_EXPIRATION=1d
      - PORT=4000
      - NODE_ENV=''
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - database
    command: sh -c "cp .env.example .env && node server.js"
  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=value
      - MYSQL_DATABASE=value
    volumes:
      - db-data:/var/lib/mysql

  # client:
  #   image: alialahmad/frontendimage:latest
  #   ports:
  #     - 80:80
  #   restart: always

volumes:
  db-data: