name: deploy to s3

on:
  push:
    branches:
      - main

jobs:
  Build-Backend-Image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        working-directory: backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backendimage:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backendimage:latest

  Build-Frontend-And-Deploy-On-S3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Check Node.js version
        run: node -v

      - name: Check npm version
        run: npm -v

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build React Project
        working-directory: ./frontend
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to S3
        run: aws s3 cp frontend/dist/ s3://comics-studio/ --recursive

  Copy-docker-compose-To-EC2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy docker-compose to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: 'docker-compose.yaml'
          target: '/home/${{ secrets.EC2_USER }}/'

  Deploy-Node-Docker:
    needs:
      [
        Build-Backend-Image,
        Build-Frontend-And-Deploy-On-S3,
        Copy-docker-compose-To-EC2,
      ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker compose down
            docker rmi ${{ secrets.DOCKER_USERNAME }}/backendimage:latest
            docker compose up -d
