name: deploy to s3

on:
  push:
    branches:
      - main

jobs:
  Build-Backend-Image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        working-directory: backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backendimage:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backendimage:latest

